# Generated by Django 5.2.7 on 2025-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(upload_to='media/')),
                ('car_name', models.CharField(max_length=25)),
                ('rent_price', models.CharField(max_length=6)),
                ('seat', models.IntegerField()),
                ('fuel', models.CharField(max_length=8)),
                ('model', models.IntegerField()),
                ('transmission', models.CharField(max_length=6)),
            ],
        ),
    ]
