# Generated by Django 5.2.7 on 2025-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_car_model',
            name='car_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
