# Generated by Django 5.2.7 on 2025-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_car_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium_Car_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=25)),
                ('pickup_location', models.CharField(max_length=20)),
                ('dropoff_location', models.CharField(max_length=20)),
                ('pickup_date', models.CharField(max_length=10)),
                ('pickup_time', models.CharField(max_length=8)),
                ('dropoff_date', models.CharField(max_length=10)),
                ('dropoff_time', models.CharField(max_length=8)),
            ],
        ),
    ]
